### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by cjohnsonuk** [geekitude/dokuwiki-plugin-userhomepage#39]
I'm on  Release 2018-04-22c "Greebo" and when I upgraded userhomepage plugin today I got error 500. Restoring the plugin folder from my backup fixed the issue.

Thought you might like to know just in case there are other issues : 
Here is the error from ssl_error_log

`[Thu Sep 10 14:37:48.358344 2020] [php7:error] [pid 9040] [client 172.16.6.1:58102] PHP Fatal error:  Uncaught Error: Call to undefined method admin_plugin_acl::deleteACL() in /var/www/html/docs/lib/plugins/userhomepage/action.php:349\nStack trace:\n#0 /var/www/html/docs/inc/events.php(229): action_plugin_userhomepage->acl(Object(Doku_Event), Array)\n#1 /var/www/html/docs/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /var/www/html/docs/inc/ActionRouter.php(88): Doku_Event->advise_after()\n#3 /var/www/html/docs/inc/ActionRouter.php(48): dokuwiki\\ActionRouter->setupAction('show')\n#4 /var/www/html/docs/inc/ActionRouter.php(60): dokuwiki\\ActionRouter->__construct()\n#5 /var/www/html/docs/inc/actions.php(16): dokuwiki\\ActionRouter::getInstance(true)\n#6 /var/www/html/docs/doku.php(120): act_dispatch()\n#7 {main}\n  thrown in /var/www/html/docs/lib/plugins/userhomepage/action.php on line 349, referer: https://xxx.xxx.xxx/docs/manuals/xxx/xxx`

**Comment by ebora** [comment]
As ACL functions were renamed for Hogfather compatibility with the last update, the up-to-date plugin version won't work with Dokuwiki versions before that. See #37

**Comment by gilcot** [comment]
Having the same issue too. For ow the workaround is to install the previous version?

**Comment by cjohnsonuk** [comment]
I got round it by moving the ./lib/plugins/userhomepage folder to a different location (effectively uninstalling the plugin) and then reinstalling the latest version.
IIRC if you don't upgrade the plugin and the wiki at the same time there's an issue.  I guess you could disable the plugin, update the wiki then update the plugin then reenable it. But I've not proved that that would work.
Hope this helps

**Comment by geekitude** [comment]
Hi.
Sorry for the late answer.
The problem is that two Dokuwiki functions used by Userhomepage for ACL rules were renamed in Hogfather.
There's not much to do against using new function names.

IMHO, your choices are:
- keep old Dokuwiki version and disable Userhomepage
- update Dokuwiki and all plugins (cjohnsonuk's hint just above is probably the easiest way to do it)
- keep outdated Dokuwiki ant edit userhomepage/action.php file to change lines 349 and 350 to : 
                            $acl->_acl_del($line['where'], $line['who']);
                            $acl->deleteACL($line['where'], $line['who']);
then wait untill you update Dokuwiki before updating Userhomepage again
