### ISSUE TITLE
PHP Warning: Undefined array keys / userhomepage/action.php

### ISSUE THREAD

**Issue by jakubglowka** [geekitude/dokuwiki-plugin-userhomepage#48]
On my dokuwiki the nginx error.log includes PHP Warnings like the following one for every page accessed by a user:
`"PHP message: PHP Warning:  Undefined array key "do" in /config/dokuwiki/lib/plugins/userhomepage/action.php on line 115; PHP message: PHP Warning:  Undefined array key "public" in /config/dokuwiki/lib/plugins/userhomepage/action.php on line 210; PHP message: PHP Warning:  Undefined array key "private" in /config/dokuwiki/lib/plugins/userhomepage/action.php on line 214"
`
How to correct it?
Is it an issue connected with the dokuwiki "Jack Jackrum"?

Installed version:  2022-08-29
PHP 8.2.13 (cli) (built: Nov 21 2023 20:24:08) (NTS)
Release 2023-04-04a "Jack Jackrum"

**Comment by Gadgetroch** [comment]
same here

**Comment by geekitude** [comment]
Hi

I'll try to fix that but it will take a few weeks since my server died.

Sorry for the inconvenience

**Comment by Gadgetroch** [comment]
Can we continue to use this plugin or it's dangerous for dokuwiki ?

**Comment by Gadgetroch** [comment]
J'ai peut être une solution pour vous aider à debugger, pouvez-vous me contacter sur mon mail ? rocco.sette@gmail.com

**Comment by geekitude** [comment]
Honestly I can't respond to that, sorry 😕

**Comment by Gadgetroch** [comment]
Voici les logs complets, si cela peut aider :

2024-04-11 12:24:20E_WARNING: Undefined array key "do"/config/dokuwiki/lib/plugins/userhomepage/action.php(115)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(115): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->redirect()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #5 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #7 /app/www/public/doku.php(131): act_dispatch()
    #8 {main}
2024-04-11 12:24:20E_WARNING: Undefined array key "public"/config/dokuwiki/lib/plugins/userhomepage/action.php(210)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(210): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->redirect()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #5 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #7 /app/www/public/doku.php(131): act_dispatch()
    #8 {main}
2024-04-11 12:24:20E_WARNING: Undefined array key "private"/config/dokuwiki/lib/plugins/userhomepage/action.php(214)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(214): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->redirect()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #5 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #7 /app/www/public/doku.php(131): act_dispatch()
    #8 {main}
2024-04-11 12:24:34E_WARNING: Undefined array key "REMOTE_USER"/config/dokuwiki/lib/plugins/userhomepage/helper.php(235)
    #0 /config/dokuwiki/lib/plugins/userhomepage/helper.php(235): dokuwiki\ErrorHandler::errorHandler()
    #1 /config/dokuwiki/lib/plugins/userhomepage/helper.php(21): helper_plugin_userhomepage->privateNamespace()
    #2 /config/dokuwiki/lib/plugins/userhomepage/action.php(93): helper_plugin_userhomepage->getPrivateID()
    #3 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->init()
    #4 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #5 /app/www/public/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
    #6 /app/www/public/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #7 /app/www/public/doku.php(125): dokuwiki\Extension\Event::createAndTrigger()
    #8 {main}
2024-04-11 12:24:34E_WARNING: Undefined array key "REMOTE_USER"/config/dokuwiki/lib/plugins/userhomepage/helper.php(32)
    #0 /config/dokuwiki/lib/plugins/userhomepage/helper.php(32): dokuwiki\ErrorHandler::errorHandler()
    #1 /config/dokuwiki/lib/plugins/userhomepage/action.php(95): helper_plugin_userhomepage->getPublicID()
    #2 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->init()
    #3 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #4 /app/www/public/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
    #5 /app/www/public/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #6 /app/www/public/doku.php(125): dokuwiki\Extension\Event::createAndTrigger()
    #7 {main}
2024-04-11 12:24:34E_WARNING: Undefined array key "REMOTE_USER"/config/dokuwiki/lib/plugins/userhomepage/action.php(97)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(97): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->init()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #5 /app/www/public/doku.php(125): dokuwiki\Extension\Event::createAndTrigger()
    #6 {main}
2024-04-11 12:24:34E_WARNING: Undefined array key "REMOTE_USER"/config/dokuwiki/lib/plugins/userhomepage/action.php(100)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(100): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->init()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #5 /app/www/public/doku.php(125): dokuwiki\Extension\Event::createAndTrigger()
    #6 {main}
2024-04-11 12:24:34E_WARNING: Undefined array key "REMOTE_USER"/config/dokuwiki/lib/plugins/userhomepage/action.php(518)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(518): dokuwiki\ErrorHandler::errorHandler()
    #1 /config/dokuwiki/lib/plugins/userhomepage/action.php(234): action_plugin_userhomepage->userOk()
    #2 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->acl()
    #3 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #4 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #5 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #6 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #7 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #8 /app/www/public/doku.php(131): act_dispatch()
    #9 {main}
2024-04-11 12:24:37E_WARNING: Undefined array key "do"/config/dokuwiki/lib/plugins/userhomepage/action.php(115)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(115): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->redirect()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #5 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #7 /app/www/public/doku.php(131): act_dispatch()
    #8 {main}
2024-04-11 12:24:37E_WARNING: Undefined array key "public"/config/dokuwiki/lib/plugins/userhomepage/action.php(210)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(210): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->redirect()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #5 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #7 /app/www/public/doku.php(131): act_dispatch()
    #8 {main}
2024-04-11 12:24:37E_WARNING: Undefined array key "private"/config/dokuwiki/lib/plugins/userhomepage/action.php(214)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(214): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->redirect()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #5 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #7 /app/www/public/doku.php(131): act_dispatch()
    #8 {main}
2024-04-11 12:24:37E_WARNING: Undefined array key "do"/config/dokuwiki/lib/plugins/userhomepage/action.php(115)
    #0 /config/dokuwiki/lib/plugins/userhomepage/action.php(115): dokuwiki\ErrorHandler::errorHandler()
    #1 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_userhomepage->redirect()
    #2 /app/www/public/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
    #3 /app/www/public/inc/ActionRouter.php(91): dokuwiki\Extension\Event->advise_after()
    #4 /app/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
    #5 /app/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /app/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
    #7 /app/www/public/doku.php(131): act_dispatch()
    #8 {main}
    
    Y'a t'il un moyen pour vous contacter de façon plus direct ?

**Comment by Gadgetroch** [comment]
Y'a t'il un moyen pour vous contacter de façon plus direct ?

**Comment by spd-spd** [comment]
This looks like a problem with moving to version 8.2 of php, not a problem with dokuwiki itself.

**Comment by jakubglowka** [comment]
> This looks like a problem with moving to version 8.2 of php, not a problem with dokuwiki itself.

Thank you for answer.
Do you mean I should try upgrading PHP to newer version or revert to the older one that is better supported by dokuwiki / userhomepage plugin?

**Comment by spd-spd** [comment]
If you feel bold enough to edit the action.php file yourself, this will get rid of the warning messages:
Line 115
// old        if (($this->multiNsOk()) and ($_GET['do'] == null)) {
        if (($this->multiNsOk()) && (($_GET['do'] ?? null) === null)) {
Line 210
// old                    if (($created['public']) && (page_exists($this->public_page))) {
                      if (($created['public'] ?? false) && (page_exists($this->public_page))) {
Line 214
// old                    } elseif (($created['private']) && (page_exists($this->private_page)) && ($this->getConf('edit_before_create'))) {
                    } elseif (($created['private'] ?? false) && (page_exists($this->private_page)) && ($this->getConf('edit_before_create'))) {

**Comment by geekitude** [comment]
Thanks for providing those correcctions.
I'll try to add them to source very soon.

Geekitude

**Comment by spd-spd** [comment]
It isn't production code level fixes; it just stops the warning messages.  My php isn't so good.

**Comment by geekitude** [comment]
Thanks for the warning 👍
